version: '3'

services:
  app:
    build: .
    container_name: 'app'
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
    links:
      - mongo
  mongo:
    container_name: db
    image: mongo
    ports:
      - 27017:27017

